name: Build JetBrains Plugin

on:
  workflow_dispatch:
    inputs:
      publish_type:
        description: 'Put `nightly` to trigger an extra, ad-hoc release of the nightly version of the extension.'
        required: false
        default: ''
      gradle_test_args:
        description: 'Additional command-line arguments passed to gradle test commands. Make sure to reference a test task, e.g. :test.'
        required: false
        default: ''
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  merge_group:
  schedule:
    - cron: '0 1 * * *' # Once per day at 1am UTC
  release:
    types: [ released ]

env:
  ENABLE_ULTIMATE: ${{ github.event_name == 'release' || github.ref == 'refs/heads/main' }}
  ORG_GRADLE_JVMARGS: "-Xmx2g -XX:MaxPermSize=1g -Dfile.encoding=UTF-8"
  GRADLE_TEST_ARGS: ${{ github.event.inputs.gradle_test_args }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: Fail on merge queue
        run: |
          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
              echo "Fail on purpose for non pull request"
              exit 1
          fi
          echo "Start to run test"
          sleep 3
          echo "Test passed"

      - name: Set job status
        id: job_status
        run: echo "status=${{ job.status }}" >> $GITHUB_ENV

      - name: Report status check
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MASON_PAT }}
          script: |
            const status = process.env.status === 'success' ? 'success' : 'failure';
            const description = status === 'success' ? 'Job 1 completed successfully' : 'Job 1 failed';
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: status,
              context: 'job-1',
              description: ${description},
              target_url: '${{ steps.job-1.outputs.url }}'
            })
